import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dispute Redressal Mechanism | NPCI National Payments Corporations",
  description: "Generated by create next app",
  themeColor: "#000000", // ✅ black status bar on Android
  appleWebApp: {
    statusBarStyle: "black-translucent", // ✅ black status bar on iOS
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
