import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadat = {
  title: "Dispute Redressal Mechanism | NPCI National Payments Corporations",
  description: "Generated by create next app",
  themeColor: "#c60d0dff", // ✅ Android Chrome status bar color
  appleWebApp: {
    statusBarStyle: "black-translucent", // ✅ iOS Safari status bar
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
